version: '3.8'

services:
  primeleague-site:
    build: .
    container_name: primeleague-site
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - npm-network

networks:
  npm-network:
    external: true
